act: leaky_relu
aug: false
batchsize: 256
channels: 1, 32, 64, 128
checkpoint_path: ./checkpoints/vanilla_resnet/vanilla_resnet-ResGRUNet-2025_05_24-16_15_51
criterion: MSELoss
dataset_folder: ./data/lmdb
dataset_name: mimic_iii
ecg: true
embed_dim: 64
enable_amp: false
es_enable: false
es_min_delta: 0.01
es_patience: 10
eval_every_n_epochs: 1
expname: vanilla_resnet
figure_path: ./figs/vanilla_resnet/vanilla_resnet-ResGRUNet-2025_05_24-16_15_51
fold: 0
fs: 125
gpu: '0'
gru: true
head_dim: 16
hidden_dim: 256
input_seq_len_s: 5
kernel_size: 7
l2norm: 0.001
lambda_contrastive: 0.0
lambda_ortho: 0.0
lambda_supervised: 1.0
loader_worker: 4
lr: 0.01
lr_linear_probe: 0.0005
lr_personalization: 0.0005
lr_scheduler_enable: true
lr_scheduler_min_lr: 1.0e-05
lr_scheduler_type: CosineAnnealingWarmupScheduler
lr_scheduler_warmup: 10
lrsched_gamma: 0.5
lrsched_step: 5, 10, 15, 20, 40
max_training_epochs: 50
mix_pretraining_subject_samples: true
model: models.ResGRUNet
model_name: ResGRUNet
n_head: 4
num_layers: 3
optimizer_type: AdamW
personalization_sample_number: 100
pooling: avg
ppg_derivatives: false
ppg_emd: false
ppg_freqs: false
pretraining_ratio: 0.8
pretraining_tr_val_tt_split_ratio: 0.7,0.1,0.2
proj_head_dim: 256
resp: false
resume: ''
return_embedding: true
seed: 42
set_tunable_params: all
sgd_momentum: 0.9
smoothl1loss_beta: 5
steps_per_epoch: 1300
supervised: false
temperature: 0.0
tensorboard_path: ./tensorboard/vanilla_resnet/vanilla_resnet-ResGRUNet-2025_05_24-16_15_51
